NybergViktor/Celemo_FrontEnd

signup.html, src/App.jsx, src/components/SignupBody/Body.css, src/components/SignupBody/Body.jsx, src/components/header/Header.jsx, src/main.jsx, src/pages/signupPage/SignupPage.jsx, src/signup.jsx, src/signupmain.jsx
=> 6 sign up page

package-lock.json, package.json, src/App.jsx, src/components/footer/Footer.jsx, src/components/header/Header.jsx
- Testa routes och kolla in koden
- Efter merge, alla måste köra "npm i" Nya moduler
Closes #24
=> routes funkar

src/App.jsx, src/components/Auction/Auction.jsx, src/components/context/AuctionContext.jsx, src/components/context/LoginContext.jsx, src/components/context/ReviewContext.jsx, src/components/context/SearchContext.jsx, src/components/context/UserContext.jsx, src/components/reviewContainerContent/reviewContainerContent.jsx, src/components/startpageMainContainer/StartpageMainContainer.jsx, src/components/userContainer/UserContainer.css, src/components/userContainerAuctions/UserContainerAuctions.jsx
Done:
Changed context fetch method to reflect changes in backend.
merge backend pr with this one
https://github.com/TommyDahlin/Celemo/pull/197
https://github.com/TommyDahlin/Celemo/pull/196
=> 50 update context to reflect new changes in backend

package-lock.json, src/App.jsx, src/components/BidSlider/BidSlider.jsx, src/components/SignupBody/Body.jsx, src/components/context/BidsContext.jsx, src/components/context/ReviewContext.jsx, src/components/context/SignupContext.jsx
Everything works but there are no error messages that pops when you do something wrong which might make it hard to know what you did wrong
Try and make an account and see if everything works
The option selects for "MALE/FEMALE" looks like shit but i got it to work which was what the issue was about
=> Signup functions, no error messages

src/App.jsx, src/components/context/BidsContext.jsx, src/components/userContainerAuctions/UserContainerAuctions.jsx, src/components/userInfoFields/UserInfoFields.jsx
Fixed so that you see your bids on profile page.
What to test:
Log in and go to profile page and see if bids show up.
Closes #41
=> users bid shows on profile page

src/App.jsx, src/components/dropDown/DropDown.jsx, src/components/dropDown/ddStyling.css, src/components/header/Header.css, src/components/header/Header.jsx
done:
Fixed styling and function, slides in from the side and looks a lot better than before.
what to check:
responsive design etc
=> fixed header, style

src/components/SignupBody/Body.css, src/components/SignupBody/Body.jsx
Done:
Fixed css on signup.
Not Done:
Background design not done.
What to test:
See if it looks good
=> Changed css on signup-page

src/components/Auction/Auction.jsx, src/components/context/BidsContext.jsx
Added a counter that checks how many bids an auction has also added a backend function
=> Counter for auctions

src/components/userContainerAuctions/UserContainerAuctions.css, src/components/userContainerAuctions/UserContainerAuctions.jsx, src/components/userContainerMyAuctions/UserContainerMyAuctions.jsx, src/pages/profilePage/ProfilePage.jsx
- Better display of information in My bids container.
- Links to auction in both My auctions and My bids.
- See if links works
Is the info good? Is there any info missing?
=> 79 profilepage fix bid container

src/components/Auction/Auction.jsx, src/components/context/BidsContext.jsx, src/components/context/UserContext.jsx
Made a new Feature that shows what user that currently has the highest winning bid.
Using a new fetch method in bidContext, sending data through state and context.
what to test:
* place a bid and see that it changes
* try other functions and see that my feature doesn't disturb other fetches or contextes
--
Closes #74
=> 74 current bid username

src/App.jsx, src/components/Auction/Auction.jsx, src/components/context/PubUserContext.jsx, src/components/context/ReviewContext.jsx, src/components/context/UserContext.jsx, src/components/footer/Footer.css, src/components/header/Header.jsx, src/components/pubprofilecomp/PubProfileComp.css, src/components/pubprofilecomp/PubProfileComp.jsx, src/components/startpageMainContainer/StartpageMainContainer.jsx, src/pages/LoginPage/LoginPage.jsx, src/pages/createReviewPage/CreateRStyle.css, src/pages/createReviewPage/CreateReview.jsx, src/pages/returnHome/ReturnHStyle.css, src/pages/returnHome/ReturnHome.jsx
* major redesign on public profile page (css and html)
And a:
* New function that lets users submit new reviews on other users.
* clickable button on public profile (review user) that leads to a new page where you can review user.
* when you have succesfully submitted a review, you will get redirected to a new page called "/return". Through this you can find back to startpage.
* your new review should look like this in MongoDB:
* log in, click into an auction, click on the sellers @, click on review user, set grade and type review text, submit
* check database
* check that id:s are correct
#note -> don't review on your own auctions
--
Tommy needs to fix pubContext before merging this PR (he knows).
--
Closes #42 
Closes #73
=> 73 create a review on user

src/App.jsx, src/components/dropDown/DropDown.jsx, src/components/footer/Footer.jsx, src/pages/contactpage/ContactPage.css, src/pages/contactpage/ContactPage.jsx
Added contact page, fixed pathing in Header, Footer and App.jsx, not sure if there's any other places where you're supposed to be able to press it.
=> Made contact page

src/components/Auction/Auction.jsx, src/pages/auction-page/AuctionPage.jsx
Flyttade sanning från Auction till Auction Page. Kort summerat har jag endast placerat det som används i auction och resten i AuctionPage som är parent.
Testa så det fungerar
Closes #69
=> moved out context and useeffect from child to parent

src/App.jsx, src/components/context/ReportsContext.jsx, src/components/context/ReviewContext.jsx, src/components/dropDown/DropDown.jsx, src/components/pubprofilecomp/PubProfileComp.jsx, src/helper/index.jsx, src/pages/adminpage/AdminPage.css, src/pages/adminpage/AdminPage.jsx
This is how it looks, it gets all reports and all reviews,
Button is just for show because i couldn't be fussed with finding how to temp ban someone. 
To test: log in with an admin account and go to localhost/admin, we have no button for it yet.
=> Made an admin page, low function

src/App.jsx, src/components/context/UserContext.jsx, src/components/userContainer/UserContainer.css, src/components/userContainer/UserContainer.jsx, src/components/userContainerMyAuctions/UserContainerMyAuctions.css, src/components/userInfoFields/UserInfoFields.jsx, src/pages/profilePage/EditProfile.css, src/pages/profilePage/EditProfile.jsx, src/pages/profilePage/ProfilePage.jsx
everything functions at the moment, haven't done extensive bugtesting…… or tried to break anything
Made an edit user page that gets accessed from your personal profile page, through a button.
You SHOULD be able to change 1 or more user info fields.
To test, change something in the edit user page and go back to your profile and see if it's changed.
=> Edit user Page

src/App.jsx, src/components/context/ReportUserContext.jsx, src/components/pubprofilecomp/PubProfileComp.css, src/components/pubprofilecomp/PubProfileComp.jsx, src/pages/reportUserPage/RUser.css, src/pages/reportUserPage/ReportUser.jsx
pages, design, functions. All done
---
ReportUserPage
&
ReportUserContext
---
Mobile:
Desktop:
---
---
---
---
What to test:
* Functionality (does it work)
* Design (any improvements?)
---
Let me know if you find anything you want to fix/change
// Viktor
Closes #100
=> 100 report user

src/App.jsx, src/components/pubprofilecomp/PubProfileComp.css, src/components/pubprofilecomp/PubProfileComp.jsx
Added so you can press an auction on someones profile and it navigates to that auction, either the auctions name or the "See more" button.
Also added so you can see the current price of an auction.
Changed the css somewhat so that the see more button changes size with the content.
To test:
Click on a users profile from some auction, check if you can go to their other auctions.
See if it looks ok in the public profiles auctions.
=> Public Profile auction

src/components/context/CreateAuctionContext.jsx, src/components/context/UserContext.jsx, src/pages/profilePage/EditProfile.css, src/pages/profilePage/EditProfile.jsx
Nu kan man ändra sin profilbild på sitt konto.
Fungerar med image url / image adress.
man får också en preview innan man klickar på submit.
=> 104 edit profile v2

src/App.jsx, src/components/Auction/Auction.jsx, src/components/context/ReviewContext.jsx, src/components/pubprofilecomp/PubProfileComp.jsx, src/components/reviewContainerContent/ReviewContainerContent.jsx
How to test:
go either to a profile or auction press on "see review"
see if it shows if you have reviews
i've added reviews to Tommy and Johansson
Viktor doesn't have any and shouldnt show any.
=> Public review dynamic

src/components/pubprofilecomp/PubProfileComp.css, src/components/pubprofilecomp/PubProfileComp.jsx
When you for example go to user johnsson84 public profile page where there is many auctions the boxes where out of place and got extremely weird with page zoom.
Changed stuff in pubProfileComp.jsx and its css.
Now when you go to someones public profile there should not be any weird glitches or containers behind containers when you try the page in different resolutions in combination with different browser zoom levels.
Closes #109
=> CSS fix in pub profile

src/components/SignupBody/Body.jsx
Added an input so you can paste a link for a photo in the signup page. 
To Test: Create a new profile and paste a url with a photo in the "Photo" box
=> Added photo for Signup

src/components/loginBody/LoginBody.css, src/pages/LoginPage/LoginPage.css
Background color was not matching figma and the rest of the app.
new:
old:
You dont need to test in branch just decide by the comparison above.
=> changed background color

src/components/Auction/Auction.jsx, src/components/footer/Footer.jsx
added so that depending if you're pressing your own name on an auction you go to your own personal profile instead of pubprofile
how to test:
Log in -> go to an auction, click on someones username, see if you go to their public profile
if you click your own auction and go to your own profile everything works
=> private profile logged in

src/components/dropDown/DropDown.jsx, src/components/footer/Footer.jsx
Log in
scroll down to footer
press logout
see if you're logged out
=> fixed logout on footer

src/components/SignupBody/Body.jsx, src/components/context/ReviewContext.jsx, src/pages/createReviewPage/CreateReview.jsx
I changed alot of stuff, changed to axios, and made it work even when you move to someone else after you've already reviewed someone. 
I've tried it a lot and think it works.
=> fixed reviews by rewriting alot of code
